version: 0.2  # 0.2 권장

phases:   # 빌드 단계
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
        - echo Pre-Build completed on `date`
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/springbootApp.jar  # 업로드 할 파일들
    - scripts/server_start.sh
    - scripts/server_stop.sh
    - appspec.yml
  discard-paths: yes # 파일명 기준으로만 업로드
cache:
  paths:
    - '/root/.m2/**/*'   # S3 cache에 등록할 파일들
